environment = "environment"
aws_access_key = "aws_access_key"
aws_secret_key = "aws_secret_key"
aws_region = "aws_region"
aws_account = "aws_account"
vpc_id = "vpc_id"
db_subnets = [ "db_subnet1", "db_subnet2" ]
allowed_security_groups = [ "allowed_security_group1", "allowed_security_group2" ]
min_aurora_capacity_units = 1
max_aurora_capacity_units = 1
db_instances = {}
db_master_password = "db_master_password"
lambda_subnets = [ "lambda_subnet1", "lambda_subnet2" ]
tags = "common_tags"