export AWS_ACCOUNT=
export AWS_REGION=
export AWS_PROFILE=

export CUSTOMER_DB_AUTH_IAM=
export CUSTOMER_DB_USER=
export CUSTOMER_DB_PASS=
export CUSTOMER_DB_NAME=
export LOCAL_CUSTOMER_DB_PORT=
export LOCAL_CUSTOMER_FUNCTION_PORT=
export CUSTOMER_FUNCTION_IMAGE_VERSION=

export ORDER_DB_AUTH_IAM=
export ORDER_DB_USER=
export ORDER_DB_PASS=
export ORDER_DB_NAME=
export LOCAL_ORDER_DB_PORT=
export LOCAL_ORDER_FUNCTION_PORT=
export ORDER_FUNCTION_IMAGE_VERSION=